pipeline{
  agent any
  
  stages{
    stage ("checkout"){
        steps{
          echo 'checkout step started'
          checkout changelog: false, poll: false, scm: [$class: 'GitSCM', branches: [[name: '^dev|master.*$']], extensions: [], userRemoteConfigs: [[credentialsId: 'jenkinsTest', url: 'https://github.com/sobbosanchinag/parentProject.git']]]
          echo 'checkout step'
        }
    }
    stage ("test"){
      steps{
        echo 'test step'
      }
    }
    stage ("deploy"){
      steps{
        echo 'deploy step'
      }
    }
  }
}
