pipeline{
  agent any
  
  stages{
    stage ("build"){
        steps{
          echo 'build step'
        }
    }
    stage ("test"){
      steps{
        echo 'test step'
      }
    }
    stage ("deploy"){
      steps{
        echo 'deploy step'
      }
    }
  }
}
